name: Deploy to heroku.

on:
  push:
    # tags:
    #   - "[0-9]+.[0-9]+.[0-9]+-a[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions.
        uses: actions/checkout@v2

      - name: Get Tag.
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Use Tag.
        run: echo ${{steps.tag.outputs.tag}}

      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.5.0
        with:
          java-version: 11
          maven-version: '3.8.4'
        
      - name: Build Spring Project
        run: mvn package

      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_directory: .
          dockerfile_name: .docker/staging.Dockerfile
          docker_options: "--no-cache"