---
name: Build, Push to Artifact Registry and Deploy to Google Kubernetes Engine
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  IMAGE_NAME: ${{ github.event.repository.name }}
  REGION: ${{ secrets.REGION }}
  REPOSITORY: ${{ secrets.REPOSITORY }}
  IMAGE_FILE: .docker/production.Dockerfile
jobs:
  build-push-to-artifact-registry:
    name: Build and Push to Artifact Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout actions
        uses: actions/checkout@v3

      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.5.0
        with:
          java-version: 11
          maven-version: '3.8.4'
        
      - name: Build Spring Project
        run: mvn package
      
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest -f $IMAGE_FILE .

      - id: 'auth'
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      
      - name: Setup Google Cloud Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}
      
      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Get Tag.
        id: tag
        uses: dawidd6/action-get-tag@v1
      
      - name: Push Docker Image to Artifact Registry
        env:
          GIT_TAG: ${{ steps.tag.outputs.tag }}
        run: |-
          docker tag $IMAGE_NAME:latest $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$GIT_TAG
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:latest
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$GIT_TAG